/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kozozgui;

/**
 *
 * @author odorn
 */
public class KozosGUI extends javax.swing.JFrame {

    /**
     * Creates new form KozosGUI
     */
    public KozosGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Ujfeladat = new javax.swing.JButton();
        Ellenorzes = new javax.swing.JButton();
        Szamolos = new javax.swing.JLabel();
        Valasz = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Kilepes = new javax.swing.JMenu();
        menuKilepes = new javax.swing.JMenuItem();
        Muveletek = new javax.swing.JMenu();
        muveletOsszead = new javax.swing.JMenuItem();
        Kivonas = new javax.swing.JMenuItem();
        Szorzas = new javax.swing.JMenuItem();
        Osztas = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alapműveletek\n");

        Ujfeladat.setText("Új feladat");

        Ellenorzes.setText("Ellenőrzés");

        Szamolos.setText("Szamolás Feladat");

        Valasz.setText("Válasz:");
        Valasz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValaszActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 218, Short.MAX_VALUE)
                        .addComponent(Ellenorzes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ujfeladat))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Szamolos, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(Valasz))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Szamolos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Valasz, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ujfeladat)
                    .addComponent(Ellenorzes))
                .addContainerGap())
        );

        Kilepes.setText("Menü");

        menuKilepes.setText("Kilépés");
        menuKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKilepesActionPerformed(evt);
            }
        });
        Kilepes.add(menuKilepes);

        jMenuBar1.add(Kilepes);

        Muveletek.setText("Műveletek");

        muveletOsszead.setText("Összeadás");
        muveletOsszead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muveletOsszeadActionPerformed(evt);
            }
        });
        Muveletek.add(muveletOsszead);

        Kivonas.setText("Kivonás");
        Kivonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KivonasActionPerformed(evt);
            }
        });
        Muveletek.add(Kivonas);

        Szorzas.setText("Szorzás");
        Muveletek.add(Szorzas);

        Osztas.setText("Osztás");
        Muveletek.add(Osztas);

        jMenuBar1.add(Muveletek);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KivonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KivonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KivonasActionPerformed

    private void menuKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKilepesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuKilepesActionPerformed

    private void ValaszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValaszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValaszActionPerformed

    private void muveletOsszeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muveletOsszeadActionPerformed
        int elsoSzam = 1 + (int) (Math.random() * 50);
        int masodikSzam = 1 + (int) (Math.random() * 50);
        
    }//GEN-LAST:event_muveletOsszeadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KozosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KozosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KozosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KozosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KozosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ellenorzes;
    private javax.swing.JMenu Kilepes;
    private javax.swing.JMenuItem Kivonas;
    private javax.swing.JMenu Muveletek;
    private javax.swing.JMenuItem Osztas;
    private javax.swing.JLabel Szamolos;
    private javax.swing.JMenuItem Szorzas;
    private javax.swing.JButton Ujfeladat;
    private javax.swing.JTextField Valasz;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuKilepes;
    private javax.swing.JMenuItem muveletOsszead;
    // End of variables declaration//GEN-END:variables
}
